### ISSUE TITLE
The Eternal Roadmap ticket

### ISSUE THREAD

**Issue by ichorid** [GuardianLabs/guardian-keyper#3]
- [x] [Implement CLA assistant](#4) 
 - [x] Add Amplitude Analytics
 - [x] Make Amplitude and Sentry dependencies optional (e.g. through compile-time defines)
 - [x] Add "Vaults" (multiple secrets per group) feature
 - [ ] Add ability to restore ownership to a guardian device
 - [ ] Internationalization
 - [ ] Remove tags in favour of guardians renaming
 - [ ] Add pure QR-based data exchange
 - [ ] Add automated unit and integration tests 
 - [ ] Implement compatibility (e.g. guardians serving) with the upcoming KeyperPro
 - [ ] Move to LedgerZero for data transfer and storage backend

**Comment by alexandrim0** [comment]
"Make Amplitude and Sentry dependencies optional" looks like it is done already (if vars not set)

**Comment by ichorid** [comment]
> "Make Amplitude and Sentry dependencies optional" looks like it is done already (if vars not set)

Yes, but the task is about making the dependencies completely optional, so the corresponding libraries are not loaded at all.
